<div class="share">
    <span class="caption"><?= /* @escapeNotVerified */ __('Share This') ?></span>
    <div class="share-item">
        <a class="facebook" href="#"><?= /* @escapeNotVerified */ __('Like') ?></a>
        <a class="divided" href="#"><?= /* @escapeNotVerified */ __('Share') ?></a>
        <span class="facebook-qty"><?= /* @escapeNotVerified */ __('235K') ?></span>
    </div>
    <div class="share-item">
        <a class="twitter" href="#"><?= /* @escapeNotVerified */ __('Tweet') ?></a>
        <span class="twitter-qty"><?= /* @escapeNotVerified */ __('93') ?></span>
    </div>
    <div class="share-item">
        <a class="pinit" href="#"><?= /* @escapeNotVerified */ __('Pin it') ?></a>
        <span class="pinit-qty"><?= /* @escapeNotVerified */ __('65K+') ?></span>
    </div>
</div>